### ISSUE TITLE
DocsTub.com New Submission

### ISSUE THREAD

**Issue by vishal-sancheti** [blimpllc/built-with-react#23]
![docstub-discover-share-earn](https://cloud.githubusercontent.com/assets/4789936/16575937/90c21d3e-42a9-11e6-9df7-7892c98bba72.png)

The link to the webapp is https://www.docstub.com, Short Info includes "A nice platform for one who invest time in making documents here they can share, discover and even earn from their original documents"

**Comment by gcollazo** [comment]
Looks good. Do you mind making a pull request?

**Comment by vishal-sancheti** [comment]
Performing a pull request please inform me what should i include.

**Comment by gcollazo** [comment]
@v1shky here are the instructions http://builtwithreact.io/about/
