### ISSUE TITLE
Taskade

### ISSUE THREAD

**Issue by johnxie** [blimpllc/built-with-react#34]
Hi!

Wanted to share http://www.taskade.com - it is built on React.
I've attached our logo and screenshot below. Thanks!

![12312314555](https://cloud.githubusercontent.com/assets/792088/22914008/315a602a-f23c-11e6-9fba-15ce1a5f9578.jpg)
![logo-text](https://cloud.githubusercontent.com/assets/792088/22914009/32ec664a-f23c-11e6-8622-c9c8f7c66847.png)

**Comment by froi** [comment]
Added.
