### ISSUE TITLE
Guilded - www.guilded.gg

### ISSUE THREAD

**Issue by iEchoic** [blimpllc/built-with-react#36]
Hey, thought I'd share [Guilded](http://www.guilded.gg) with you all, which recently launched and is 100% React.

![Image of Guilded landing page](http://i.imgur.com/opTlaPC.png)

Would love to have it listed on your page. Thanks!

**Comment by froi** [comment]
Thanks for the submission and sorry it took so long for us to get to this. [Here you are](http://builtwithreact.io/2018/01/14/guilded/)
