### ISSUE TITLE
Company's website built with React

### ISSUE THREAD

**Issue by mateusz-brainhub** [blimpllc/built-with-react#40]
![brainhub-web](https://user-images.githubusercontent.com/17500172/34780835-7ad2c93a-f624-11e7-91b0-66454ed32289.png)

**Comment by froi** [comment]
Hi @mateusz-brainhub could you share the link to the site?

**Comment by froi** [comment]
I'm closing this issue. There has been no response in 16 days.

**Comment by mateusz-brainhub** [comment]
HI @froi sorry for a 'bit' late reply. Here you have -> [Brainhub](https://brainhub.eu/)
